### ISSUE TITLE
JSON file is invalid (has markdown appended)

### ISSUE THREAD

**Issue by flcdrg** [lycheeverse/lychee-action#100]
When specifying the JSON format and saving to a file, an extra bit of markdown text is appended, causing the JSON to be invalid.

Using the action like this

```yaml
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.4.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: '--verbose ./_posts/**/*.md --exclude-mail --scheme http https'
          format: json
          output: ./lychee/links.json
          fail: false
```

eg. here's the end of the resulting JSON file

```json
    "./_posts/2011/2011-11-01-springtime-in-garden.md": [
      {
        "url": "http://msmvps.com/blogs/bill/archive/tags/Life/default.aspx",
        "status": "Failed: Network error"
      }
    ]
  }
}[Full Github Actions output](https://github.com/flcdrg/myproject/actions/runs/2089026665?check_suite_focus=true)

```
I think the culprit is https://github.com/lycheeverse/lychee-action/blob/master/entrypoint.sh#L28

I don't think this should be appended if the format is JSON
