### ISSUE TITLE
Usage example Action does not create issue upon finding broken links

### ISSUE THREAD

**Issue by chipzoller** [lycheeverse/lychee-action#144]
Hi, thanks for this very nice action! I copied-and-pasted from your [Usage instructions](https://github.com/lycheeverse/lychee-action#usage) to my repo and ran the action. It found a number of broken links but did not create any issue. I see in the action log `echo ::set-output name=exit_code::2` but it did not trigger the `if: steps.lychee.outputs.exit_code != 0` clause.

**Comment by mre** [comment]
Yeah I think that part is broken right now. 

We expose the lychee exit code as an output parameter:
https://github.com/lycheeverse/lychee-action/blob/a520e851a79326b0ca0f11d8537a2b58a416f876/entrypoint.sh#L45

**However** lychee-action doesn't expose this output to other steps outside the composite action.
My guess is that we need add a section like [this](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-docker-container-and-javascript-actions) to `action.yml`:

```yml
outputs:
  exit_code:
    description: "Lychee exit code"
    value: ${{ steps.lychee.outputs.exit_code }}
runs:
  using: "composite"
  steps:
    ...
```

Maybe we should also change the output name to `exit-code` to follow the conventions in the Github Actions documentation?
