### ISSUE TITLE
How to pass arguments correctly?

### ISSUE THREAD

**Issue by abordage** [lycheeverse/lychee-action#155]
I decided to disable email verification. Workflow:

```yml
name: Check Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * 1"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: --exclude-mail
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
```

Job output:
```bash
Run /home/runner/work/_actions/lycheeverse/lychee-action/v1.5.1/entrypoint.sh
  /home/runner/work/_actions/lycheeverse/lychee-action/v1.5.1/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
    INPUT_GITHUB_TOKEN: 
    INPUT_ARGS: --exclude-mail
    INPUT_FORMAT: markdown
    INPUT_OUTPUT: lychee/out.md
    INPUT_FAIL: false
    INPUT_JOBSUMMARY: true
+ LYCHEE_TMP=/tmp/lychee/out.md
+ GITHUB_WORKFLOW_URL='https://github.com/XXX'
++ dirname /tmp/lychee/out.md
+ mkdir -p /tmp/lychee
+ ARGS=--exclude-mail
+ FORMAT=
+ [[ --exclude-mail =~ --format  ]]
+ FORMAT='--format markdown'
+ eval lychee --format markdown --output /tmp/lychee/out.md --exclude-mail
++ lychee --format markdown --output /tmp/lychee/out.md --exclude-mail
error: The following required arguments were not provided:
    <inputs>...

USAGE:
    lychee <inputs>... --config <config-file> --exclude-mail --format <format> --github-token <github-token> ...
```

It works, If use multiple arguments:
```yml
uses: lycheeverse/lychee-action@v1.5.1
with:
 args: --verbose --no-progress  --exclude-mail './README.md'
```

But doesn't work with one argument `--exclude-mail`

**Comment by abordage** [comment]
Ок. Correct disabling check email:
```yaml
uses: lycheeverse/lychee-action@v1.5.1
with:
  args: --verbose --no-progress --exclude-mail './**/*.md' './**/*.html'
```
