### ISSUE TITLE
Doubled output with fail=true and exit code 1 in GitHub summary

### ISSUE THREAD

**Issue by tooomm** [lycheeverse/lychee-action#163]
When `fail = true` is enabled and the exit code is not 0, the job will fail as expected.
However, it leads to a wrong (and doubled) GitHub Summary output.

The table from a different, successful earlier lychee step in the same job is picked up and appended to the summary again.

<br>

I've two checks in one job:
```
      - uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: '<some args> -- <file1>'
          fail: true
          jobSummary: true

      - uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: '<some args> -- <file2>'
          fail: true
          jobSummary: true
```

Each step puts out its own summary table, and the second step appends their output to the first one resulting in a job summary of two different tables below each other normally.
With the second step running into exit code 1 (file not found), I see the output from the first check two times now in GitHub's job summary.

**Comment by mre** [comment]
Ah I know why this is happening and the explanation is pretty simple of course: we use the same output file; it's hard-coded to `lychee/out.md`.

The question is what to do about that. I'm guessing we could randomize the output file name. That should be enough.
So like `out-4930234903.md` or something.

**Comment by mre** [comment]
@tooomm I created #173 to partially resolve the issue.
We now write the initial temporary output to a truly random temporary file.


I don't know if we should change the behavior of concatenating the final output of multiple runs into one file.
It could be seen as a feature because the output destination is deterministic.
If we change it we'd have to come up with a naming scheme for the output files
and a normal user would have to figure out where the final output is located to do
any post-processing.

You can prevent the output merging by assigning different output filenames manually, e.g.

```yaml
      - uses: lycheeverse/lychee-action@master
  with:
    args: '<some args> -- <file1>'
    output: run1.md
    fail: true
    jobSummary: true

- uses: lycheeverse/lychee-action@master
  with:
    args: '<some args> -- <file2>'
    output: run2.md
    fail: true
    jobSummary: true
```

Does that work for you?
