### ISSUE TITLE
Replace `set-output` by `$GITHUB_ENV`

### ISSUE THREAD

**Issue by Yury-Fridlyand** [lycheeverse/lychee-action#166]
Hi

https://github.com/lycheeverse/lychee-action/blob/2e991c588d2d66f0622b3b6a96bda71b28afaf67/entrypoint.sh#L51
`set-output` function of GHA is deprecated. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
It is recommended to use `Environment files` instead. An example from GHA docs:
```
steps:
  - name: Set the value
    id: step_one
    run: |
      echo "action_state=yellow" >> $GITHUB_ENV
  - name: Use the value
    id: step_two
    run: |
      echo "${{ env.action_state }}" # This will output 'yellow'
```
