### ISSUE TITLE
Checking only links from modified files in a Pull Request?

### ISSUE THREAD

**Issue by polarathene** [lycheeverse/lychee-action#17]
This is a feature that [`github-action-markdown-link-check`](https://github.com/gaurav-nelson/github-action-markdown-link-check#check-only-modified-files-in-a-pull-request) offers.

Could this action support that as well? (_or document advice on how to provide only relevant file paths to check_)

---

Almost 18 months later, I revisited this request, comments of interest are:

- [Advice for Github request/API rate limits](https://github.com/lycheeverse/lychee-action/issues/17#issuecomment-1162586751), which for PR workflows from third-party contributors lack secrets access (_60 requests per hour limit_). Affects link checking on Github services (_eg: Github repo file/issue/pr links, or github pages_).
  - Related [production branch scheduled runs with persisted cache](https://github.com/lycheeverse/lychee-action/issues/134#issuecomment-1163985468).
- [Initial advice for getting line specific content, or relevant files from the PR changes](https://github.com/lycheeverse/lychee-action/issues/17#issuecomment-1162854596).
  - Related, [individual line content changes feed to `lychee` via STDIN input is ill-advised depending on content/context](https://github.com/lycheeverse/lychee-action/issues/134#issuecomment-1163985468).
- [Final advice for using two different approaches to collect relevant files to check, and then pre-process for compatibility to action input `args` in `lychee-action`](https://github.com/lycheeverse/lychee-action/issues/17#issuecomment-1172098729).
- [Detailing `xargs` as viable for `lychee`, but not `lychee-action` as a user](https://github.com/lycheeverse/lychee-action/issues/17#issuecomment-1172787687). Requested a separate `lychee-action` input, or for `lychee` an `--inputs-from` option.

---

## Examples - Workflows that can be used currently

The first two support file paths containing spaces.

Without considering file paths containing spaces; if a mistake is made or a third-party contributor provides a file path containing a space, `lychee` will treat that path as separate files/inputs which would be invalid (_or the wrong files to check_).

### Manually generating the file paths to check

I [looked into this extensively](https://github.com/actions/checkout/issues/520#issuecomment-1167205721), and I'm rather confident of this approach.

<details>
<summary>Click to view YAML</summary>

- Remove or adjust the [`--diff-filter` option](https://git-scm.com/docs/git-diff-tree#Documentation/git-diff-tree.txt---diff-filterACDMRTUXB82308203) as appropriate to your needs. View the `git diff-tree` docs linked for other options that may be of interest such as ignoring white-space only changes.
- The `sed` command is specifically for `lychee-action` needs. It folds the multi-line output of `git diff-tree` (`\n` / line delimited list of file paths_) into a single line, separating paths with single quotes and later in the `lychee-action.args` input adding single quotes to the start/end, so that file paths can support spaces when provided as a single line to `eval` (_which `lychee-action` uses internally_). This handling is not required for `lychee`, which can instead replace `sed` with `xargs -d '\n' lychee --`.

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      # Compares the default generated "test merge commit" by Github (HEAD) to the base branch (HEAD^1)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Gets a list of files from the PR with a git status of Added (A) or Modified (M)
      - name: 'Example - Get a list of changed files to process'
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff-tree --name-only --diff-filter 'AM' -r HEAD^1 HEAD | sed -z "s/\n$//;s/\n/' '/g")
          echo "::set-output name=all_changed_files::${CHANGED_FILES}"

      - name: 'Check Links'
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --verbose --no-progress -- '${{ steps.changed-files.outputs.all_changed_files }}'
```

</details>

### Delegate to `tj-actions/changed-files` action to get the file paths

After this PR is resolved, the pre-processing step for `lychee-action` can likely be dropped and the output of [`tj-actions/changed-files`](https://github.com/tj-actions/changed-files) provided to a new input for `lychee-action` that handles the delimited list of paths internally.

<details>
<summary>Click to view YAML</summary>

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      # Compares the default generated "test merge commit" by Github of the PR branch into the base branch
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Gets a list of files from the PR with a git status of Added (A) or Modified (M) | (via outputs.all_changed_files)
      - name: 'Example - Get a list of changed files to process'
        id: get-changed-files
        uses: tj-actions/changed-files@v23
        with:
          separator: ','

      # lychee-action requires pre-processing for file paths with spaces (boundary quotes added in lychee-action input):
      - name: 'Compatibility with eval: Quote wrap paths to support spaces'
        id: changed-files
        run: |
          QUOTE_WRAPPED="$( sed "s/,/' '/g" <<< '${{ steps.get-changed-files.outputs.all_changed_files }}' )"
          echo "::set-output name=all_changed_files::${QUOTE_WRAPPED}"

      - name: 'Check Links'
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --verbose --no-progress -- '${{ steps.changed-files.outputs.all_changed_files }}'
```

</details>

### Simpler version when file paths of inputs would never contain spaces

If you are confident that this won't be a concern to support, the extra pre-processing step can be avoided.

**NOTE:** If adapting to the "manual" example, you must still convert `\n` to space, unless [`lychee` gets a `--inputs-from` option](https://github.com/lycheeverse/lychee/issues/662#issuecomment-1169679959), then you can provide a file with `git diff-tree` output directly (_or [without writing an actual file](https://github.com/lycheeverse/lychee/issues/662#issuecomment-1172789465)_).

<details>
<summary>Click to view YAML</summary>

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      # Compares the default generated "test merge commit" by Github of the PR branch into the base branch
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Gets a list of files from the PR with a git status of Added (A) or Modified (M) | (via outputs.all_changed_files)
      - name: 'Example - Get a list of changed files to process'
        id: get-changed-files
        uses: tj-actions/changed-files@v23

      - name: 'Check Links'
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --verbose --no-progress -- ${{ steps.changed-files.outputs.all_changed_files }}
```

</details>

**Comment by mre** [comment]
Hey that's a good feature to have. I checked the code (https://github.com/gaurav-nelson/github-action-markdown-link-check/blob/master/entrypoint.sh#L155) and it doesn't seem too hard to port.

**Comment by polarathene** [comment]
I glanced over the link you gave and it seems to be using git for the diff which makes sense, but I'm not sure how well that works with some relative URLs or other forms of post-processing where it might differ vs comparing two builds (eg `gh-pages` branch of current deployment vs PR build output from a CI job testing build is successful).

If you do add the feature it would be good to document usage. As in this would test PR diff files between branches, to test a diff against other use-cases, the user should have an earlier CI step generate a diff and pass it through to the `lychee-action` input arguments manually?

**Comment by mre** [comment]
Just to clarify, the diff checking would exactly work like in  [github-action-markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check#check-only-modified-files-in-a-pull-request) because we'd use the same code. So if that works for you, we should be all set. 😄

**Comment by polarathene** [comment]
Well old me did link to it, so presumably that's roughly what I wanted :sweat_smile: 

I'm a bit busy lately, so I won't be able to try out such a feature any time soon. I would like to revisit the CI and give it a go if `lychee-action` adds the support. Presently we don't have any link checking in our CI, other than what our docs build process offers (relative md links).

**Comment by tooomm** [comment]
I like this idea a lot! Is this still something that you plan on adding?

**Comment by luisorbaiceta** [comment]
This would be amazing! I was doing some testing to add the action to the fastify repo, but it reaches the api rate limit easily for github links

**Comment by polarathene** [comment]
@luisorbaiceta 

> but it reaches the api rate limit easily for github links

### Internal links workaround via local webserver

If the links are internal, you could run a simple webserver (Caddy is quite easy). At least I assume Github has no restrictions for links that aren't external traffic? (_I tried looking up docs on rate limits, but only found mention of these applying to APIs or to products/services Github hosts_)

If your internal links to test aren't able to be replaced/mapped to `localhost` for that local webserver instance, then you should be able to add hostname into `/etc/hosts` and that should work well.

---

### Minimizing requests

#### Prioritize reachable hosts, then individual links

For external links, I suppose the best options available to minimize requests would be caching the FQDN availability and only checking the first request to each unique FQDN, then afterwards you could check all other links are actually valid, not just the host for it is reachable.

#### Leverage the response cache

I still haven't got to try lychee out yet, but the devs did add [response caching support](https://github.com/lycheeverse/lychee/issues/163) a while back. If you're hitting the limit due to frequency of runs, leveraging that caching feature across runs should make a big difference :)

---

### Workaround for rate-limit

For restricted network requests, I did see [this issue](https://github.com/lycheeverse/lychee-action/issues/97), where they are apparently hitting limits because of some links to Github hosted services, which suggested excluding these with a lychee option. You could always have a scheduled workflow that checks your links daily (or hourly) with the response caching in place for working around that hourly limit (with the cache being a larger TTL like 24 hours).

Assuming responses that get `Network error: Too Many Requests` response can be tried again by this workflow next time. You could then have any 404's and the like reported via an action that raises an issue listing them. If you have multiple scheduled runs in a day, you could cache those 404 responses separately across runs for the final daily task to report.

You would probably want to have such workflows (or this action in general) be conditionally run only if querying the current available requests for the hour is still sufficient to support any other workflows you have that may need to perform Github API requests.

**Comment by polarathene** [comment]
@tooomm 

> The file basis doesn't help me actually as it's all in one file already. :see_no_evil:
> Would that also be possible and do you consider this a useful addition?

Do you really need filtering to individual lines for a single file? If you don't have any problems you're trying to avoid, you'll have better reliability with processing the entire file through `lychee` from what I found. If you want that functionality, you can implement it in your CI workflow to pass to `lychee` as shown below.

---

Here is an example that retrieves the diff from [this commit](https://github.com/docker-mailserver/docker-mailserver/commit/d4ba2b7f5027a2868e19c68fcba41b34b2bad1fd) (docs deployment from Github Actions). I haven't tried integrating with the `lychee-action` or PRs yet (_where you'd do the same with the PR diff Github generates_)

### Line diff scope (individual lines per file):

```bash
# Get lychee:
$ docker run --rm -it rust bash
$ cargo install lychee

# Example repo with a branch of deployed docs, clone it to get a diff from desired commit
$ git clone https://github.com/docker-mailserver/docker-mailserver -b gh-pages
$ cd docker-mailserver

# Finally show a specific commit diff (default format is -p for patch), and only show diff for files with `.html` suffix,
# Then filter to addition/modification lines (green lines on github, starts with +),
# And feed these lines into lychee to parse for any links:
$ git show d4ba2b7f5027a2868e19c68fcba41b34b2bad1fd '*.html' | grep '^+' | lychee -
🔍 3 Total ✅ 3 OK 🚫 0 Errors
```

It successfully parsed the 3 links in files that were changed. `lychee -` will take links via STDIN, so we can read a commit diff, filter it and send it to `lychee` this way. I'm not familiar with how `lychee` is extracting links, I thought I'd have to extract out the `href` values as I didn't provide a proper HTML doc, but nope `lychee` is great! :grinning: 

```console
# For context, these are the 3 filtered lines of that commit:
$ git show d4ba2b7f5027a2868e19c68fcba41b34b2bad1fd '*.html' | grep '^+' | grep 'href'

+<p><a href="https://github.com/docker-mailserver/docker-mailserver/blob/master/target/postfix/main.cf">Our default Postfix configuration</a> can easily be extended to add parameters or modify existing ones by providing a <code>docker-data/dms/config/postfix-main.cf</code>. This file uses the same format as Postfix <code>main.cf</code> does (<a href="http://www.postfix.org/postconf.5.html">See official docs</a> for all parameters and syntax rules).</p>
+<p>One can easily increase the <a href="http://www.postfix.org/postconf.5.html#compatibility_level">backwards-compatibility level</a> and set new Postscreen options:</p>
```

It doesn't have to be an existing commit just a diff, or any other approach you have of collecting only the changed lines and feeding those into `lychee`.

The [merged commit for the PR associated to that docs deployment](https://github.com/docker-mailserver/docker-mailserver/commit/0010786d181a3a6c70856d4c34e46b60ad015b7e) commit has different files/content but works just as well with the same technique, so it could be used on the source files (_in my case PR content differs for external and internal links, with the latter being relative links that the build tool handles_):

```console
$ git show 0010786d181a3a6c70856d4c34e46b60ad015b7e '*.md' | grep '^+' | lychee -   
🔍 3 Total ✅ 3 OK 🚫 0 Errors

# Just to show the same links that are found:
$ git show 0010786d181a3a6c70856d4c34e46b60ad015b7e '*.md' | grep '^+' | grep 'http'

+[Our default Postfix configuration](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/postfix/main.cf) can easily be extended to add parameters or modify existing ones by providing a `docker-data/dms/config/postfix-main.cf`. This file uses the same format as Postfix `main.cf` does ([See official docs](http://www.postfix.org/postconf.5.html) for all parameters and syntax rules).
+    One can easily increase the [backwards-compatibility level](http://www.postfix.org/postconf.5.html#compatibility_level) and set new Postscreen options:
```

---

I'm assuming a bit more work would be needed to verify link references are valid. The link referenced may not have changed, but there might be a typo in the reference name or the referenced link itself was accidentally not added by the contributor.

The approach above won't work, an example is from [this markdown docs commit](https://github.com/docker-mailserver/docker-mailserver/commit/4cb617f7f90bc8716601f2a07cbae8a001da30e0#diff-4fc68afe0a571d0ca897f75f6ba00f8d36b78a3c02c57276c0abc6285794a09bR123):

```markdown
- SASLauthd with LDAP auth (please see the note [down below](#ldap-setup))

...

Add these additions to the `mailserver` service in your [`docker-compose.yml`][github-file-compose]:
```

The first references a heading (`#ldap-setup`), the 2nd references a link at the bottom of the document `github-file-compose`, but that information won't be available to lychee from the changes input. [It doesn't appear that this is checked/supported yet](https://github.com/lycheeverse/lychee/issues/456#issuecomment-1010149220), so matters less.

These kind of changes, would be local file issues, which could be handled via a separate pass (_or alternatively preferring to check links against build output, not source files_). Thus `lychee` could ignore that link reference syntax for diff-based checks.

---

Actually... perhaps `lychee` lacks context for STDIN approach. I didn't see any options to hint content (HTML, Markdown, etc), so while markdown file works with the equivalent content, providing it to `lychee` via STDIN flops:

```bash
echo -e '[test](./relative/path/to/file.md)\n\n[test-ref][ref-file]\n\n[ref-file]: ./relative/path/to/another/file.md' \
  | lychee --dump -
```

---

### File-level diff scope (file paths of changed files)

If you don't need granular line changes, you can detect which files were changed instead and provide just these files to `lychee` to look through.

This was a bit confusing for me to figure out how to get the list of file paths as args to `lychee`, especially if for some reason a space existed in one of the file paths:

```bash
# --no-commit-id --name-only will list only file paths involved in the commit.
# --diff-filter 'AM' is filtering the files in the diff to only be ones added (A) or modified (M).
# -r (recursive) is to include files in sub-directories, so that all files belonging to the commit are listed.
# HEAD references the latest commit, but could be a commit hash like previous examples.
# '*.md' like above is to filter files to only those with '.md' extension/suffix, uses gitignore syntax,
# ':!README.md' shows how to add more filter patterns, this one excludes with ':!' the top-level 'README.md' file.
#
# xargs splits the multi-line output by '\n' (defaults don't seem to work well with this git diff-tree output), and
# provides each line to lychee as a separate arg, spaces in filepath will be fine, as if quote wrapped.

git diff-tree --no-commit-id --name-only --diff-filter 'AM' -r HEAD '*.md' | xargs -d '\n' lychee --dump --
```

This should be more reliable, for other types of link support since actual files will be parsed. Leverage the response cache feature and file-level scope for changes should work very close to changed lines scope. At least assuming your `lychee-action` workflow is triggered multiple times for PR iterations.

### File or line scope for PR branch diff

For PRs, if you're wanting to compare changes from the PR branch to a target branch (eg: `master` / `main`), then you'll want to use [`--merge-base`](https://git-scm.com/docs/git-diff-tree#Documentation/git-diff-tree.txt---merge-base) with `git diff-tree` command [I think](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-git-diff-comparison)?

```bash
# Example with --merge-base, can reference by commit hashes, branch names, or any "tree-ish" value:
# https://stackoverflow.com/questions/4044368/what-does-tree-ish-mean-in-git/18605496#18605496
# The PR would be the 2nd value, to get it's additions/modifications when added to the 1st (eg: master branch)
# Make sure your checked out branch is the 2nd one being compared, otherwise if a file does not exist,
# lychee will attempt to request the filepath over http.. '--offline' is for links found, '--skip-missing' however would prevent the request attempt.
git diff-tree --no-commit-id --name-only --diff-filter 'AM' -r --merge-base master remote/branch-name | xargs lychee --dump --

# Same syntax, but swaps '--name-only' for '-p' and adds a filter with grep to output changed lines:
git diff-tree --no-commit-id -p --diff-filter 'AM' -r --merge-base master some-local-branch | grep '^+ ' | lychee --dump -
```

Note that if you have lots of filepaths, you may exceed the character limit for args I think. `lychee` doesn't appear to have support for taking in a list of paths (from STDIN or file) which would probably be a safer approach.

**Comment by polarathene** [comment]
**NOTE:** I compared the reference link script for getting the file diff to my approach here, and noticed it has some issues with [this line](https://github.com/gaurav-nelson/github-action-markdown-link-check/blob/228fbf4ffb2a86a65314866e9b2322b519fd885f/entrypoint.sh#L171).

I tried it on my local repo to compare the master branch (new commits since my PR) and my PR branch and `git diff --name-only --diff-filter=AM "$MASTER_HASH"` was including files that weren't from my PR but added/modified since in the `master` branch. Those shouldn't be part of the PR diff of changed files.

It had a few other issues, that I report [here](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/118) (_an issue with one of the problems in the script, raised in Sep 2021, no interaction from maintainers since_). I'd be careful with porting that shell script into this action due to those issues that have been in that repo for several years without being resolved (_personally it's these kinda of gotchas which make me loathe shell scripts_).

**Comment by mre** [comment]
Thanks for the heads-up @polarathene.
I wonder if anyone tried do something like this:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.0
        with:
                args: --verbose --no-progress ${{ steps.changed-files.outputs.all_changed_files }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ```

⚠️ I did not test this, so there are most likely syntax errors in the above code.

**Comment by luisorbaiceta** [comment]
> fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
I guess the problem with this in PRs would be to set the fetch depth dynamically to ensure all files modified in the PR are checked

**Comment by polarathene** [comment]
> I wonder if anyone tried do something like this

I can probably give it a try later.

Looking at the action that generates the file list, I think it's offering space ~~or `,` as delimiter between file paths, `lychee` wouldn't work with `,` delimiter right?~~ (_**EDIT:** `,` was for the `csv` format (although it does seem to be a single `,` delimited string anyway..), there's also `json`_) But space delimiter would also not work for file paths with spaces in them (_I try avoid this, but I bring it up as some users projects do have that concern_),

I am not sure how the output is applied, either as one large string arg, or what I think happens is interpolation to generate the value to parse as if it was provided explicitly (_thus quote wrapping each list value would preserve spaces where they should be_). 

The JSON output would probably be a bit too specific to support, unless you integrate it internally with a composite action like another PR for this action was looking into?

The `git diff-tree` commands I shared earlier should work just as well to get the file paths, but `xargs` could not be used to populate the actions `args`, it'd require different pre-processing (probably with `sed`) to generate quote wrapped file paths.

A more compatible option that'd work with both this action and lychee directly, would be to support [an option to provide inputs via a line delimited list](https://github.com/lycheeverse/lychee/issues/662) (eg from a file). This avoids another concern (limits on arg length in shells), and less hassle transforming to args formatted in a way that `lychee` accepts without the gotchas involved with shell values (_just look at the referenced action [examples for using shell on the CSV and JSON outputs to extract values](https://github.com/jitterbit/get-changed-files#get-all-added-and-modified-files-as-csv)_).

---

I didn't manage to try with `lychee` yet, but I did manage to have some luck with earlier commands I shared and getting that to work as desired with GH Actions ([a little bit more detail covered in this comment](https://github.com/rmacklin/fetch-through-merge-base/issues/1)):

```yaml
name: 'Documentation (PR)'
on:
  pull_request:
    paths:
      - 'docs/**'

concurrency:
  group: docs-pullrequest-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pr-link-check:
    name: 'Docs - Check Links (PR)'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout PR and all PR commits + 1'
        uses: actions/checkout@v3
        # Get the HEAD commit, not the merge commit GH generates for PR and fetches by default
        # I'm not sure why, but `git log` shows the number of commits as sufficient without the +1,
        # but otherwise seemed necessary when I tested locally without GH Actions
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: ${{ github.event.pull_request.commits }}

      - name: 'Example: Show files added/modified by PR branch'
        # Referencing via ENV vars only for better readability compared to the context expressions
        env:
          BRANCH_PR: ${{ github.event.pull_request.head.ref }}
          BRANCH_BASE: ${{ github.event.pull_request.base.ref }}
        run: |
          # Enabling echo for testing, so that you can see the output in workflow logs
          echo '::echo::on'
          # Get the base branch to derive the common ancestor commit (aka merge-base)
          # By default git fetch will try find a common commit in local history, else fetch all commits
          git fetch origin "${BRANCH_BASE}"
          # echo -e here is just to make the output visible to the logs
          echo -e "$(git diff-tree --no-commit-id --name-only --diff-filter 'AM' -r --merge-base origin/"${BRANCH_BASE}" "${BRANCH_PR}")"
```

It doesn't seem to show anything with the default merge commit that is fetched, but I guess that commit would contain the changed files info all in a single commit instead of the extra work shown above?

**Comment by polarathene** [comment]
<details>
<summary>Failed attempt with xargs</summary>

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 'A - Get a list of changed files to process'
        id: changed-files-a
        run: |
          # Gets a diff of files from git with Added (A) or Modified (M) status,
          # Compares the default generated "test merge commit" by Github (HEAD) to the base branch (base.sha == HEAD^1),
          # `sed` then converts from multi-line (`\n`) to single-line delimited by `,` to support file paths containing spaces:
          CHANGED_FILES=$(git diff-tree --name-only --diff-filter 'AM' -r HEAD^1 HEAD | sed -z 's/\n/,/g;s/,$//')
          echo "::set-output name=all_changed_files::${CHANGED_FILES}"

      # Same output as prior step:
      - name: 'B - Get a list of changed files to process'
        id: changed-files-b
        uses: tj-actions/changed-files@v23
        with:
          separator: ','

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --verbose --no-progress $( xargs -d ',' <<< "${{ steps.changed-files-a.outputs.changed_files }}" )
```

</details>

The usage of `xargs` is required due to `lychee` not supporting inputs sourced from a file, the inputs need to be provided with white-space in mind for paths, so `,` was used as a delimiter to split on (_when not using `lychee-action`, I could split the `git diff-tree` output on `\n` instead_).

I thought this would work due to `eval` being used (which AFAIK is advised against):

https://github.com/lycheeverse/lychee-action/blob/76ab977fedbeaeb32029313724a2e56a8a393548/entrypoint.sh#L17

But... as it turns out this did not work. I realized to make it `eval` compatible as well, I'd need to quote wrap paths... This was problematic as the inputs are being escaped (_possibly to [prevent security vulnerabilities described here](https://cycode.com/blog/github-actions-vulnerabilities/), but perhaps some malicious file paths with the `eval` approach could still risk damage?_).

I had trouble trying to make that approach work. I gave up and added another intermediate step which works:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 'A - Get a list of changed files to process'
        id: changed-files-a
        run: |
          # Gets a diff of files from git with Added (A) or Modified (M) status,
          # Compares the default generated "test merge commit" by Github (HEAD) to the base branch (base.sha == HEAD^1),
          # `sed` then converts from multi-line (`\n`) to single-line delimited by `,` to support file paths containing spaces:
          CHANGED_FILES=$(git diff-tree --name-only --diff-filter 'AM' -r HEAD^1 HEAD | sed -z 's/\n/,/g;s/,$//')
          echo "::set-output name=all_changed_files::${CHANGED_FILES}"

      # Same output as prior step:
      - name: 'B - Get a list of changed files to process'
        id: changed-files-b
        uses: tj-actions/changed-files@v23
        with:
          separator: ','

      # lychee-action requires pre-processing for file paths with spaces
      # NOTE: Github outputs and ENV do not support `\n`, so rely on single-line string or read/write a file
      - name: 'Compatibility with eval: Quote wrap paths to support spaces'
        id: changed-files
        env:
          # Change between a or b step above:
          changed_files: ${{ steps.changed-files-a.outputs.all_changed_files }}
        run: |
          QUOTE_WRAPPED="'$( sed "s/,/' '/g" <<< '${{ env.changed_files }}' )'"
          echo "::set-output name=all_changed_files::${QUOTE_WRAPPED}"

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --verbose --no-progress ${{ steps.changed-files.outputs.all_changed_files }}
```

So not being able to use `xargs` option rules out the alternative I had in mind with using a file to avoid all the extra transforms to make the paths compatible args (_I've sunk a fair amount of time messing with shell incantations to try figure this out, with plenty of failures that other users should not have to go through as well I hope_).

I did try messing around with `printf '%s'` variants with `xargs` and `readarray`, but when using `xargs -d` I would end up with extra `\n` at the end that I couldn't strip off, and would end up as part of the last item path (if quote wrapping), or it's own item `$'\n'` with `printf '%q'`, with `readarray` involved as well I avoided that with `printf '%s\n'`, but it was getting long/ugly and with `eval` involved, seemed easier to just quote wrap with sed.

---

It'd probably be better for `lychee-action` to support a new _`file-list` input_ that can take a `,` delimited string as a list of inputs? (_simpler to support `tj-actions/changed-files` or similar, than having `lychee` support inputs from a file_)

I did not have much luck looking up GH actions limits for input lengths which might be a problem on larger projects?

Alternatively not supporting file paths with spaces for `lychee-action` would avoid the hassle to support above.
