### ISSUE TITLE
Security: Make SHA-pinning effective (e.g. allow pinning SHA of Docker image)

### ISSUE THREAD

**Issue by trevyn** [lycheeverse/lychee-action#19]
GitHub recommends [pinning third-party Actions to a commit SHA](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions), but since `lycheeverse-action` pulls a Docker image, that image should also be able to be pinned to a specific SHA.

To prevent churn, one approach could be to simply allow passing a Docker image SHA into the script from the end-user's `.yml`, which, if present, would then be used to pin the Docker image.

See, for example: https://github.com/returntocorp/bento/issues/318

Another approach: An option to have the action build `lychee` from scratch, which would be slower, but would also further reduce the attack surface.

**Comment by mre** [comment]
Oh I didn't know that was possible. 

Just tested; this works as expected:

```
docker pull lycheeverse/lychee:0.5.1-alpha@sha256:efe2bf21aca4acaf3449fcd432a0ed49ccf33c0ee9ae5c94849d5a3d430392ec
```

But I'm not sure I understand.
lychee-action is not pulling Docker images directly afaik? The Docker image gets pulled by Github Actions on build.
So wouldn't it be enough if people added the SHA themselves like so?

```yml
- name: Link Checker
  uses: lycheeverse/lychee-action@v1.0.4@sha256:...
```

It's likely that I'm missing something.

**Comment by booyaa** [comment]
@mre I think you're right in that people using the action should do this themselves. Perhaps update the documentation? I'd be willing to have a crack at it.

Read a bit more about this security hardening strategy and it looks like people using the actions can use dependabot to automatically patch with the sha digest: https://francoisbest.com/posts/2020/the-security-of-github-actions

It's a relatively easy  thing to apply

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: ".github/workflows" # Location of package manifests
    schedule:
      interval: "daily"
```
