### ISSUE TITLE
Bug: not possible to output JSON to file

### ISSUE THREAD

**Issue by jasongitmail** [lycheeverse/lychee-action#198]
There seems to be bug that prevents outputting JSON to a file. Could it be the lack of `INPUT_OUTPUT` within [`action.yml`](https://github.com/lycheeverse/lychee-action/blob/master/entrypoint.sh), given it defaults the value of output currently to `--output ${LYCHEE_TMP}`?

My workaround is to run the lychee action step to install it, but then to follow with a separate step using lychee: `- run: lychee <otherArgs> --format json --output ./links.json`.

**Comment by jasongitmail** [comment]
Unfortunately, there seems to still be something awry. 

I tested `uses: lycheeverse/lychee-action@master`

Then I also ran `ls -la` for a number of directories after running lychee-action to try to find the file saved it somewhere unexpected, but it wasn't anywwhere to be found. I also tried a filename that does not have a directory in the path, since my actual path does, in case that made a difference, but same result. I'm using the same command that otherwise works with lychee directly as the args for the action.

**Comment by mre** [comment]
Ah, so you overwrite `--output`, in your args right?
So you have something like

```yaml
- name: Link Checker
  uses: lycheeverse/lychee-action@master
  with:
    args: --output foo.txt ...
```

If so, this is a bit tricky, because it is currently not used.
Instead, the recommended way is to set the additional `output` argument for the action and *not* set it in `args`:

```yaml
- name: Link Checker
  uses: lycheeverse/lychee-action@master
  with:
    # Check all markdown and html files in repo (default)
    args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'
    # Use json as output format (instead of markdown)
    format: json
    # Use different output file path <-- That's what you're looking for
    output: /tmp/foo.json
```

This puts the output into `/tmp/foo.json`. The default is `lychee/out.md`, relative to the working directory of the action.

Can you try that?

If it's not possible, I can change it such that it uses `--output` from the `args` if it is set. This should avoid the confusion for users. We already do something similar for `--format`: https://github.com/lycheeverse/lychee-action/blob/5a5fc0bef7bcf1858217e7c9a8d4c01ec79dbeaf/entrypoint.sh#L18-L22

But first, I'd like to learn if setting `output: /tmp/foo.json` works for you.

If I misunderstood, can you paste your workflow here?
