### ISSUE TITLE
Action exit code is not set 

### ISSUE THREAD

**Issue by lenisha** [lycheeverse/lychee-action#20]
Th Lychee action exit code is not reflected in the job

Example run:
https://github.com/lenisha/linkchecker-test/runs/2117110939?check_suite_focus=true
```
    steps:
      - uses: actions/checkout@v2
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.0.4
        with:
          args: --exclude="^(javascript|chrome):.*"   --accept=200,403,429 "**/*.md" "**/*.html"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
```

Although Lychee step exits with status code 2, next steps does not get the exit code properly, it gets 0 instead of 2:
```
+ lychee '--exclude=^(javascript|chrome):.*' --accept=200,403,429 '**/*.md' '**/*.html' --output /tmp/lychee/out.md
+ exit_code=2
+ '[' 2 -ne 0 ']'
++ dirname lychee/out.md
+ mkdir -p lychee
+ echo 'Errors were reported while checking the availability of links:'
+ cat /tmp/lychee/out.md
+ cat /tmp/lychee/out.md
+ echo ::set-output name=exit_code::2
📝 Summary
---------------------
🔍 Total..........519
✅ Successful.....462
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded........53
🚫 Errors...........4

Errors in python/auto_examples/plot_train_convert_predict.html
✗ https://scikit-learn.org/stable/modules/preprocessing.html/nPlease [404 Not Found]

Errors in docs/reference/execution-providers/Nuphar-ExecutionProvider.md
✗ https://support.microsoft.com/en-us/help/841290 [404 Not Found]

Errors in docs/how-to/build.md
✗ https://cmake.org/files/v3.13/cmake-3.16.1.tar.gz [404 Not Found]
✗ https://www.raspberrypi.org/downloads/raspbian/ [404 Not Found]::set-output name=exit_code::2
1s
Run exit 
  exit 
  shell: /usr/bin/bash -e {0}
```
