### ISSUE TITLE
Q: Can we check a live website online as lychee can

### ISSUE THREAD

**Issue by zierbeek** [lycheeverse/lychee-action#207]
Hi,

I would like to setup an automatic action to check my personal website online. 

What would i need to create if i want to check www....com every week? 

Thanks!

**Comment by mre** [comment]
Something like this should work:

```yml
name: Links

on:
  schedule:
    - cron: "00 8 * * 1" # check at 8am on Monday

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose https://example.com

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
```
