### ISSUE TITLE
How to `--dump` to file?

### ISSUE THREAD

**Issue by tooomm** [lycheeverse/lychee-action#214]
It looks like `--dump` only prints the found links to the console.

I would like to dump the extracted links to a file to further work with it.
Not sure how to do this with the action.

`output:` is not considered, or I'm not sure of the actual location 🤔

**Comment by mre** [comment]
Whoops, then let me move it back to lychee-action. Apologies for the confusion.
You can decide where the file ends up in the action.

```yaml
- name: Link Checker
  uses: lycheeverse/lychee-action@master
  with:
    # Check all markdown and html files in repo (default)
    args: --base . --dump './**/*.md' './**/*.html' './**/*.rst'
    # Use different output file path
    output: /tmp/foo.txt
``` 

The default path currently is `lychee/out.md` (as defined in the [action.yml](https://github.com/lycheeverse/lychee-action/blob/master/action.yml)).
If the output does not end up there, that's a bug.

To reuse the output in a downstream job that depends on this job, see ["Defining outputs for jobs"](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) in the GitHub Docs.

**Comment by tooomm** [comment]
Thanks again for trying to help here, mre!

>You can decide where the file ends up in the action.

That's correct.
As stated in the issue description, I was using `output` and was not able to spot the file when trying various possibilities.
Same actually, when using the default location and not using a custom path for output.

So the question is still the same... :D
Can not tell if it's a bug or me being the issue here.

>To reuse the output in a downstream job that depends on this job, see ["Defining outputs for jobs"](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) in the GitHub Docs.

It should only be used in a subsequent step within the same job.

Can you provide me a working example that e.g. prints the file afterwards in a following step in the action?
Taking your above example here, how to print the `foo.txt` file for example... I could not find/link the file in my tests.

```
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Output
        uses: lycheeverse/lychee-action@v1
        with:
          # Check all markdown and html files in repo (default)
          args: --base . --dump './**/*.md' './**/*.html' './**/*.rst'
          # Use different output file path
          output: /tmp/foo.txt
    
      - name: Print Output
        shell: bash
        run: cat ???
```

**Comment by LilDrunkenSmurf** [comment]
So I'm running into a similar situation, where when I pass in the `output` command, it fails: https://github.com/LilDrunkenSmurf/k3s-home-cluster/actions/runs/7309944973/job/19918081978#step:4:110
I setup debug, and tried to print the output, and I noticed it's not evaluating the second `if` statement here: https://github.com/lycheeverse/lychee-action/blob/ef8c8f32c278e9eed290c6e6c96748f16b6cd335/entrypoint.sh#L33

It looks like it runs the `if` statement above, , and evaluates it to false, and carries on, but skips the next one.

Rather than making it two different if statements, perhaps it should be nested.

Something like:

```
# Ensure we have any output
if [ ! -f "${LYCHEE_TMP}" ]; then
    echo "No output. Check pipeline run to see if lychee panicked." > "${LYCHEE_TMP}"
else if
	# If we have any output, create a report in the designated directory
    mkdir -p "$(dirname -- "${INPUT_OUTPUT}")"
    cat "${LYCHEE_TMP}" > "${INPUT_OUTPUT}"

    if [ "${INPUT_FORMAT}" == "markdown" ]; then
        echo "[Full Github Actions output](${GITHUB_WORKFLOW_URL})" >> "${INPUT_OUTPUT}"
	fi
fi
```

**Comment by mre** [comment]
Cool. Can you send a pull request with that change, so we can test it?

**Comment by LilDrunkenSmurf** [comment]
Tested the PR, and it looks good.

**Comment by mre** [comment]
Also added an integration test for `--dump` specifically. https://github.com/lycheeverse/lychee-action/pull/218

**Comment by tooomm** [comment]
Finally got around to have a look again.

What I want to archive
- Parse a file as input and dump the URLs into a md file
- Check the URLs from the dumped md file as input for lychee

See my config:
```
      # Extract URLs
      - name: Extract URLs
        uses: lycheeverse/lychee-action@v2
        with:
          args: --dump --exclude www.w3.org -- input.xml
          output: lychee/url_list.md
          jobSummary: false

      # Print output
      - name: Print List of URLs
        run: cat ./lychee/url_list.md

      # Check dumped URLs from file
      - name: Check URLs
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --require-https -- './lychee/url_list.md'
          jobSummary: true
```

The first step succeeds and the file is dumped.
The second steps succeeds and the dumped output file is found + printed.
The third step is failing and the output file can not be found and used as input.
```
Error: Cannot parse inputs from arguments

Caused by:
    Invalid file path: ./lychee/url_list.md
```

Any idea?
