### ISSUE TITLE
Setting `output` arg does not write results to disk

### ISSUE THREAD

**Issue by onedr0p** [lycheeverse/lychee-action#216]
Hi 👋🏼 

I have the action set up like this, however it always fails on the `Print Output` step because it cannot find `/tmp/results.md`. I've tried setting the `output` arg to `./lychee/results.md` as well but that still does not work. For some reason it seems like the action is not writing the output to the file, meanwhile I see the results in stdout.

```yaml
      - name: Checkout Default Branch
        uses: actions/checkout@v4

      - name: Scan For Broken Links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --exclude-mail './**/*.md'
          format: markdown
          output: /tmp/results.md

      - name: Print Output
        run: cat /tmp/results.md

      - name: Find Link Checker Issue
        id: find-issue
        shell: bash
        run: |
          issue_number=$( \
              gh issue list \
                  --search "in:title ${{ env.WORKFLOW_ISSUE_TITLE }}" \
                  --state open \
                  --json number \
                  | jq --raw-output '.[0].number' \
          )
          echo "issue-number=${issue_number}" >> $GITHUB_OUTPUT
          echo "${issue_number}"

      - name: Create or Update Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "${{ env.WORKFLOW_ISSUE_TITLE }}"
          issue-number: "${{ steps.find-issue.outputs.issue-number || '' }}"
          content-filepath: /tmp/results.md
```

```
Run cat results.md
  cat results.md
  shell: /usr/bin/bash -e {0}
  env:
    WORKFLOW_ISSUE_TITLE: Link Checker Dashboard 🔗
    lychee_exit_code: 0
cat: /tmp/results.md: No such file or directory
Error: Process completed with exit code 1.
```
