### ISSUE TITLE
lychee-action produces no output and doesn't seem to do anything

### ISSUE THREAD

**Issue by alebcay** [lycheeverse/lychee-action#24]
I've tried using lychee-action v1.0.7 or v1.0.8 and see runs like [this](https://github.com/alebcay/awesome-shell/runs/2412855766?check_suite_focus=true) happening. It looks like nothing is actually running as part of the action?

The workflow file is here:
```
name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request:

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check links
        uses: lycheeverse/lychee-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: cat ./lychee/out.md
        if: ${{ always() }}
```

Not sure if I'm just doing something wrong or if there has been some kind of a regression.
