### ISSUE TITLE
Opened issue everyday

### ISSUE THREAD

**Issue by Isengo1989** [lycheeverse/lychee-action#268]
Hey there,

if the action is run on a schedule, the issue is created every day again and again till solved. This gives a little bit of a push to solve it, otherwise you sometimes rely on other resources to fix the link. Is there an easy way to avoid that?

**Comment by mre** [comment]
Hey @Isengo1989,

can you try out these instructions for reusing/updating existing issues? https://lychee.cli.rs/github_action_recipes/reuse-issue/

**Comment by Isengo1989** [comment]
Hey @mre 

Great thx, did not know about those docs :wave: 

One thing I noticed is the missing **id** in the  **Find Link Checker Issue** step that is used. I will create a PR on it.

I also added an extra if check to verify it was found. Wdyt ?

```
      - name: Find Link Checker Issue
        uses: micalevisk/last-issue-action@v2
        id: known-issue
        with:
          state: open
          labels: |
            link-checker

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0 && steps.known-issue.outputs.has-found != 'true'
        uses: peter-evans/create-issue-from-file@v5
        with:
          issue-number: "${{ steps.known-issue.outputs.issue-number }}"
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: link-checker
```
