### ISSUE TITLE
Links malformed in actions output

### ISSUE THREAD

**Issue by Aariq** [lycheeverse/lychee-action#271]
I love this action, but I'd love it even more if I could just click the links in the GitHub actions output (see screenshot).  They currently print out in markdown as [url](url) and when I click them, it takes me to `url](url)` which is not a valid website.

E.g. If I click on this first link in the screenshot, I get taken to <https://dev.mysql.com/downloads/connector/odbc/](https://dev.mysql.com/downloads/connector/odbc/)>

![Image](https://github.com/user-attachments/assets/70cf8b8f-d321-4ed7-b76a-7567ddb664ac)

Here's the actual failing action: https://github.com/cct-datascience/group-procedures/actions/runs/13076688563/job/36490500223

**Comment by mre** [comment]
We can try to fix it, but I don't know how to make the links clickable in GitHub actions. Any docs/references or other actions which support that?

**Comment by Aariq** [comment]
I think if it just printed out as the bare URL it might "just work".

**Comment by mre** [comment]
Alright, can somebody confirm that this is the case? Changing it would totally be possible then. 👍

**Comment by mre** [comment]
I tested it with a simple workflow:

```yaml
name: URL Format Test

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Bare URL
        run: |
          echo "https://dev.mysql.com/downloads/connector/odbc/"
          
      - name: Test with echo -e
        run: |
          echo -e "https://dev.mysql.com/downloads/connector/odbc/"
```

Bot tests worked like a charm. 
That means we can change that. It would be a change in the [lychee](https://github.com/lycheeverse/lychee) repo, though.
