### ISSUE TITLE
Checkbox Formatting Option for Markdown Reports

### ISSUE THREAD

**Issue by Arteiii** [lycheeverse/lychee-action#274]
Follow up for https://github.com/lycheeverse/lychee/pull/1623

**Comment by Arteiii** [comment]
Maybe add a new action argument, like checkbox. So you could use it like this:

```yml
- name: Run lychee
  uses: lycheeverse/lychee-action@v2
  with:
    checkbox: true
```
