### ISSUE TITLE
Support annotations

### ISSUE THREAD

**Issue by dveeden** [lycheeverse/lychee-action#275]
Related: https://github.com/lycheeverse/lychee/issues/1637

This is what I got working:

`.github/lychee-problem-matcher.json`:
```json
{
	"problemMatcher": [
		{
			"owner": "lychee",
			"pattern": [
				{
					"regexp": "^\\[(.*)\\]:$",
					"file": 1
				},
				{
					"regexp": "^\\s*\\[ERROR\\] (.*)$",
					"message": 1,
					"loop": true
				}
			]
		}
	]
}
```

```yaml
      - run: echo "::add-matcher::.github/lychee-problem-matcher.json"
      - name: Link Checker
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: lycheeverse/lychee-action@v2.3.0
        with:
          fail: true
          args: --root-dir $(pwd) -E -i -n -t 45 -- '${{ steps.changed-files.outputs.all_changed_files }}'
          format: compact
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NO_COLOR: 1
```

Resulting in this:

![Image](https://github.com/user-attachments/assets/6ed531eb-7cb0-42c0-9754-acdd8b56a6f3)

![Image](https://github.com/user-attachments/assets/6fd98218-a69c-422b-976c-97b42d40b432)

However the line number is missing in the output, so the annotation doesn't get added to the right place in the file
