### ISSUE TITLE
Network error: Forbidden

### ISSUE THREAD

**Issue by mprinkezs** [lycheeverse/lychee-action#282]
Hi,

Checking links to a specific website frequently results in "Network error: Forbidden", but opening the same URLs in a webbrowser does not reveal any problem.

Example:
https://github.com/ZEISS/zeiss-inspect-app-examples/actions/runs/13854906022

Thanks in advance for checking this!

Best regards,
Matthias

**Comment by mre** [comment]
The MySQL docs seem to block unknown user agents.
Using the curl user agent works:

```sh
❯❯❯ echo https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlconnection-connect.html | lychee --user-agent "curl/8.4.0" -vvv -
     [200] https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlconnection-connect.html
 ```

Can you try this?

```yaml
name: Links
on:
  workflow_dispatch:
  push:
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --user-agent "curl/8.4.0" --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
```

See also https://lychee.cli.rs/troubleshooting/network-errors/#try-a-different-user-agent
