### ISSUE TITLE
GitHub rate limiting despite default `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by jan-ferdinand** [lycheeverse/lychee-action#289]
Hi there, thank you for your work on lychee as well as this github action. ❤

Recently, I started having CI failures due to GitHub's rate limiting, which hadn't happened before with this action.[^fail] As far as I understand, the lychee binary picks up on and uses the `GITHUB_TOKEN` environment variable by default, which should prevent rate limiting issues. It's not obvious how any of the recent commits to either this action or to lychee itself would have changed this behavior. Unfortunately, I'm at a bit of a loss: why is [my action](https://github.com/TritonVM/triton-vm/actions/runs/14749141210/workflow) being rate limited?

[^fail]:  [This](https://github.com/TritonVM/triton-vm/actions/runs/14749141210) is the most recent failure at the time of writing.

**Comment by GlenDC** [comment]
I see the same issue in my project: https://github.com/plabayo/rama/blob/f96ee2867e6211b7e50a28ef5f6da1d89c775188/.github/workflows/links.yml#L19

this always has worked before, do we need a different API key perhaps that has more bandwidth?

**Comment by mre** [comment]
Oh, I'm not aware of any breaking changes. We haven't changed the checking algorithm.

Looking at your summary, I noticed that you have 741 links.

```
# Summary
| Status        | Count |
|---------------|-------|
| 🔍 Total      | 741   |
| ✅ Successful | 288   |
| ⏳ Timeouts   | 0     |
| 🔀 Redirected | 0     |
| 👻 Excluded   | 1     |
| ❓ Unknown    | 0     |
| 🚫 Errors     | 452   |
```

I checked the pipeline and noticed that you run the link check on every push to `master` and every PR targeting `master.
So you could be hitting GitHub API rate limits if you have more than two such events per hour.
Not all of these links have to be GitHub links, but they quickly add up!

Another issue appears in your workflow logs:
```
[WARN] Cache is too old (age: 39d 20h 34m 25s, max age: 1d 0h 0m 0s). Discarding and recreating.
```

So, in summary, I guess you're facing two problems:
1. GitHub API rate limiting (1,000 requests per hour per repository)
2. Cache not updating when the link check fails

Here's what you could try:

```yaml
on:
  workflow_dispatch:
  push:
    branches:
      - master
  # TODO: Remove this section:
  # pull_request:
  #  branches:
  #    - master
  schedule:
    - cron: "0 0 * * *"

- name: Restore lychee cache
  id: restore-cache
  uses: actions/cache/restore@v4
  with:
    path: .lycheecache
    key: cache-lychee-${{ github.sha }}
    restore-keys: cache-lychee-

- name: Link Checker
  uses: lycheeverse/lychee-action@v2.3.0
  id: lychee_run
  with:
    args: |
      --cache
      --verbose
      --no-progress
      '.'
  continue-on-error: true

- name: Save lychee cache
  uses: actions/cache/save@v4
  if: always()
  with:
    path: .lycheecache
    key: ${{ steps.restore-cache.outputs.cache-primary-key }}
```

This solution splits the cache operations into separate restore and save steps and uses `if: always()` to ensure the cache is saved even when the link check fails. I haven't tried it, but I'd be thankful if you gave it a shot. We can update the docs accordingly if it works, because I guess a lot of people might run into this problem now or in the future as their repos grow.

The part about the workflow triggers at the start of the YAML file isn't strictly necessary. I think the important part is to get the cache fixed.

@GlenDC, looking at a [recent run](https://github.com/plabayo/rama/actions/runs/14913043971), I can also see that you have a lot of links:

```md
# Summary

| Status        | Count |
|---------------|-------|
| 🔍 Total      | 1434  |
| ✅ Successful | 1309  |
| ⏳ Timeouts   | 0     |
| 🔀 Redirected | 0     |
| 👻 Excluded   | 44    |
| ❓ Unknown    | 0     |
| 🚫 Errors     | 81    |
```

It looks like only around 300 of the 1434 links are GitHub links, though, and you only run lychee once per day so that's weird. 

My hunch is, that you run into a secondary rate limiting problem with GitHub as described in [the docs](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits):

> In addition to primary rate limits, GitHub enforces secondary rate limits in order to prevent abuse and keep the API available for all users.
>
> You may encounter a secondary rate limit if you:
> 
> - Make too many concurrent requests. No more than 100 concurrent requests are allowed. This limit is shared across the REST API and GraphQL API.

So if more than 100 requests to GitHub run concurrently (and it's likely since lychee can run way more requests concurrently), you might be unfortunate enough to be rate-limited.

Can you try to set the max-concurrency lower for a test?
`--max-concurrency 20 --max-retries 0` or so.

Also, can you add a cache similar to how @jan-ferdinand does it in their pipeline?

**Comment by GlenDC** [comment]
> Can you try to set the max-concurrency lower for a test?
> --max-concurrency 20 --max-retries 0 or so.

Currently I do not set any args myself.
Can you recommend me what exactly to change in https://github.com/plabayo/rama/blob/main/.github/workflows/links.yml please?

**Comment by mre** [comment]
```yaml
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.4.0
        with:
          args: --base . --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst' --max-concurrency 20 --max-retries 0
          token: ${{ secrets.GITHUB_TOKEN }}
```
