### ISSUE TITLE
Fix for for Stack Overflow checks resulting in "Network error: Forbidden"?

### ISSUE THREAD

**Issue by mprinkezs** [lycheeverse/lychee-action#294]
Checks like https://stackoverflow.com/questions/7367976/calling-a-c-sharp-library-from-python/ used to succeed in the past, but are now resulting in "Network error: Forbidden".

Does anyone have a hint on how to fix this?

I am using

```
 - name: Linkcheck
        id: lychee
        if: ${{ env.SUBDIR_NAME != 'merge' }}
        uses: lycheeverse/lychee-action@v2
        with:
          args: --user-agent "curl/8.4.0" --base . --verbose --no-progress '${{ env.SUBDIR_NAME }}/**/*.html'
```

in https://github.com/ZEISS/zeiss-inspect-app-api.
