### ISSUE TITLE
Error: Is a directory (os error 21)

### ISSUE THREAD

**Issue by irongut** [lycheeverse/lychee-action#3]
I'm attempting to switch from peter-evans/link-checker to  lycheeverse/lychee-action but I'm getting an error whenever my workflow runs:
```
Run lycheeverse/lychee-action@v1
/usr/bin/docker run --name cc49563e5ee5548076440b9eeed26b8e62143a_aa2ec5 --label cc4956 --workdir /github/workspace --rm -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/EliteALD/EliteALD":"/github/workspace" cc4956:3e5ee5548076440b9eeed26b8e62143a -E -i -v *
+ LYCHEE_OUT=lychee/out.md
+ LYCHEE_TMP=/tmp/lychee/out.md
++ dirname /tmp/lychee/out.md
+ mkdir -p /tmp/lychee
+ lychee -E -i -v '*' --output /tmp/lychee/out.md
Error: Is a directory (os error 21)
```

Here is my workflow:
```
name: Link Checker v2 (Lychee)
on:
  schedule:
  - cron: 0 1 * * *
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1
      with:
        args: -E -i -v *
    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_TITLE: Link Checker Report
        ISSUE_CONTENT_FILEPATH: ./lychee/out.md
        ISSUE_LABELS: report, automated issue
```

Can you suggest what I've done wrong?
