### ISSUE TITLE
Create issue from file usage?

### ISSUE THREAD

**Issue by NissesSenap** [lycheeverse/lychee-action#36]
Hi

I wonder how to use the issues from file in the cronjob. It looks like the example in the README is broken.

```
name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: --verbose --no-progress **/*.md **/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
```

`--output out.md` isn't defined and thus we will never create any issue.

My understanding of https://github.com/peter-evans/create-issue-from-file is that it will create a issue with the data from the file no matter what it says in it.

lychee don't have any flag where you only create a file if you get an error, or have I missed something?
So we need to add some small script to first check if the output file generate only have 0 Errors in it.
If errors is 0 remove the file.

I will write a small script for this and create a PR for the README.

If i missed something please point me in the correct direction.
