### ISSUE TITLE
Comment on existing PR instead

### ISSUE THREAD

**Issue by abitrolly** [lycheeverse/lychee-action#40]
Can the `lychee-action` comment on existing PR if link check fails instead of creating another issue?

**Comment by mre** [comment]
Yes, you can set the issue number of an existing issue to update.
The [docs](https://github.com/peter-evans/create-issue-from-file) describe how:

```yaml
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
          issue-number: 1
```

**Comment by abitrolly** [comment]
I mean if a person submits a PR, the report goes into that PR comment. Is that possible?

**Comment by mre** [comment]
Oh sorry, I didn't read that correctly.

Although I haven't tried it, adding a comment to a PR should be possible with
https://github.com/peter-evans/create-or-update-comment

This will need some tweaking, but generally that's how you could do it:

```
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build output
            ${{ steps.lychee.outputs.content }}
```

`${{ steps.lychee.outputs.content }}` is not set. Perhaps we should set it in the action to the contents of `./lychee/out.md`? Otherwise you have to use something like https://github.com/marketplace/actions/cat-for-github-actions at the moment (unless I'm missing something).
