### ISSUE TITLE
Error with base dir `<empty>` : Found absolute local link

### ISSUE THREAD

**Issue by seb-celinedesign** [lycheeverse/lychee-action#44]
I'm checking html files passing a folder arg to Lychee : 
```yaml
      - name: Link checker
        uses: lycheeverse/lychee-action@v1.0.8
        id: lychee
        with:
          args: --verbose --no-progress --exclude=w3.org --exclude=schema.org --exclude-mail build/client/**/*.html
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
```
Since today, i've the following error :
```
Error: Error with base dir `<empty>` : Found absolute local link "/favicons/apple-touch-icon.png" but no base directory was set. Set with `--base`.
```
I never used the `base` arg and it's worked fine until today.
Anything related to [this issue](https://github.com/lycheeverse/lychee/issues/320) ?
