### ISSUE TITLE
Given example usage does not work

### ISSUE THREAD

**Issue by T145** [lycheeverse/lychee-action#46]
I'm using the same general format as the workflow, but it does not work:
```yaml
name: Check Sources

on:
  #repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  check_sources:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Check Links
        uses: lycheeverse/lychee-action@v1
        with:
          args: -vin -T 4 -m 5 sources/sources.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Dead Source Report
          content-filepath: ./lychee/out.md
          labels: bug
```
The failure check is there b/c otherwise the reporting will not run. Even with it there, the file reporter cannot seem to find the lychee report.

GitHub links are also giving a 403 response, even w/ the GitHub token provided.
