### ISSUE TITLE
Issues are created regardless of result

### ISSUE THREAD

**Issue by fregante** [lycheeverse/lychee-action#60]
The readme states:

> issues will be created when the action finds link problems.

That's not currently correct.

I ran the suggested workflow and got this issue:

- https://github.com/refined-github/refined-github/issues/5114

I fixed the links and then a new issue was opened, empty:

- https://github.com/refined-github/refined-github/issues/5116

For this to happen, `lychee-action` should probably export a variable that I can then pass to the next action. For example:

```yml
       - uses: lycheeverse/lychee-action@v1.1.1
         id: lychee 
         with:
           args: --verbose --no-progress **/*.md **/*.html
         env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
       - name: Create Issue From File
         if: steps.lychee.outputs.errors
         uses: peter-evans/create-issue-from-file@v3
         with:
           title: Link Checker Report
           content-filepath: ./lychee/out.md
```
