### ISSUE TITLE
Latest builds failing with RegEx parsing issue

### ISSUE THREAD

**Issue by dend** [lycheeverse/lychee-action#67]
See example job [on OpenSearch](https://github.com/opensearch-project/OpenSearch/runs/4612946161?check_suite_focus=true):

```
Pattern syntax error near position 0: recursive wildcards must form a single path component
```

I've noticed the same problem on my own blog (private repository). Any thoughts on what might be causing it?

The job I am running is mapped to the following YAML file:

```
name: Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Load Excludes
        run: |
          LYCHEE_EXCLUDE=$(sed -e :a  -e 'N;s/\n/ /;ta' .lycheeexclude)
          echo "LYCHEE_EXCLUDE=$LYCHEE_EXCLUDE" >> $GITHUB_ENV

      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          args: --accept=200,429 --exclude ${{ env.LYCHEE_EXCLUDE }} --exclude-mail "**/*.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
```
