### ISSUE TITLE
The lychee exit status doesn't seem to be be propagated correctly through the action (by default)

### ISSUE THREAD

**Issue by dkarlovi** [lycheeverse/lychee-action#71]
I have the action currently setup like this:

```yaml
            -
                name: Link Checker
                uses: lycheeverse/lychee-action@master
                with:
                    args: --verbose --offline --base ./tests/functional/init/public ./tests/functional/init/public
```

It [gives me this output](https://github.com/sigwinhq/yassg/runs/4950590137?check_suite_focus=true):
```
+ LYCHEE_TMP=/tmp/lychee/out.md
+ GITHUB_WORKFLOW_URL='https://github.com/sigwinhq/yassg/actions/runs/1750502305?check_suite_focus=true'
++ dirname /tmp/lychee/out.md
+ mkdir -p /tmp/lychee
+ ARGS='--verbose --offline --base ./tests/functional/init/public ./tests/functional/init/public'
+ FORMAT=
+ [[ --verbose --offline --base ./tests/functional/init/public ./tests/functional/init/public =~ --format  ]]
+ FORMAT='--format markdown'
+ lychee --format markdown --output /tmp/lychee/out.md --verbose --offline --base ./tests/functional/init/public ./tests/functional/init/public
Error: Failed to read file: `./tests/functional/init/public`, reason: Is a directory (os error 21)
+ exit_code=1
+ '[' 1 -ne 0 ']'
++ dirname -- lychee/out.md
+ mkdir -p lychee
+ cat /tmp/lychee/out.md
cat: /tmp/lychee/out.md: No such file or directory
+ echo '[Full Github Actions output](https://github.com/sigwinhq/yassg/actions/runs/1750502305?check_suite_focus=true)'
+ cat /tmp/lychee/out.md
cat: /tmp/lychee/out.md: No such file or directory

+ echo

+ echo ::set-output name=exit_code::1
+ '[' false = true ']'
```

But the action passed? Seems the exit code from any of the commands didn't get propagated correctly.
