### ISSUE TITLE
Use composite action for issue creation

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee-action#74]
See [this blog post](https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/) on the topic and the [Github documentation](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action). 

This way our example code would change from this:

```yaml
name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: ${{ steps.lychee.outputs.exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
```

to this

```yaml
name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

We would still use `peter-evans/create-issue-from-file`, but it would be done internally.

Issue creation could be disabled as well

```yaml
- name: Link Checker
  uses: lycheeverse/lychee-action@v1.1.1
  with:
    create_issue: false
```
