### ISSUE TITLE
How to test GH wikis?

### ISSUE THREAD

**Issue by kaihendry** [lycheeverse/lychee-action#8]
E.g. https://github.com/cheeaun/life/wiki/Lives has a lot of bad links... any suggestions how to check pages like that?

Many thanks!

**Comment by pawroman** [comment]
Hi! It seems that all you need to do is point lychee at that address.

Try this:

```
- name: Link check wiki using lychee
  uses: lycheeverse/lychee-action@v1
  with:
    args: -v https://github.com/cheeaun/life/wiki/Lives
```

Note that for GitHub links you're likely to need the GitHub token. Please see https://github.com/lycheeverse/lychee#github-token for more details.
