### ISSUE TITLE
Fails to resolve link to source file in private repo from action

### ISSUE THREAD

**Issue by lukehsiao** [lycheeverse/lychee-action#89]
I'm seeing a discrepancy between the behavior of the github action and running lychee locally.

I have a link checking step configured as follows:
```
jobs:
    check_links:
        name: Link Checking
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Link Checker
              uses: lycheeverse/lychee-action@v1.3.2
              with:
                  fail: true
                  args: -E --verbose --no-progress './**/*.md' './**/*.html'
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

One of the links in a document is to a particular source file in a private github repository:

```
## Errors per input
### Errors in CHANGELOG.md
* [https://github.com/private/repo/blob/main/src/file.py](https://github.com/private/repo/blob/main/src/file.py): Failed: Network error when trying to connect to an endpoint via hubcaps
```

However, when running the same command locally:

```
$ lychee  -E --verbose './**/*.md' './**/*.html'
```

It appears to check fine:

```
https://github.com/private/repo/blob/main/src/file.py [200 OK]
```

This is with `lychee 0.8.2` locally, which should match the 1.3.2 github action.

My hypothesis is that when provided the GitHub token, the lychee action is taking a different code path than it is without that on the CLI. Is that correct? Is there a way to get matched behavior?

**Comment by mre** [comment]
Might be an issue with the token scope.
You can try to use the same Github token you use locally for CI. 
Something like 

```yaml
- name: Link Checker
  uses: lycheeverse/lychee-action@v1.3.2
  with:
      fail: true
      args: -E --verbose --no-progress './**/*.md' './**/*.html'
  env:
      GITHUB_TOKEN: ${{secrets.CUSTOM_GITHUB_TOKEN}}
```

where `CUSTOM_GITHUB_TOKEN` will be set in the project configuration.
Maybe that helps.

**Comment by lukehsiao** [comment]
Following-up, that seems to be exactly the issue. In particular, it seems that the default `secrets.GITHUB_TOKEN` does not allow access to repositories *outside* of the one it is being run in, whereas a custom token can.

So, in my case I cannot check links to private_repo_2 from an action in private_repo_1, due to the scope of GITHUB_TOKEN.

Everything appears to be working as expected, so I will go ahead and close this issue.

**Comment by paddyroddy** [comment]
@mre what permissions should I have on my `CUSTOM_GITHUB_TOKEN`. I have `Metadata: Read` and have tried `Contents: Read & write` but am getting this

```
[404] https://github.com/UCL-MIRSG/UCLMedicalImagingEnv/blob/main/environments/cs-production/xnat/group_vars/ucl_test/vars | Network error: Not Found
```

This is a private repo within the same organisation.

**Comment by mre** [comment]
The permissions should be fine, but have you passed your custom token into the pipeline? See my code sample above. 

```yaml
      args: ...
  env:
      GITHUB_TOKEN: ${{secrets.CUSTOM_GITHUB_TOKEN}}
where 
```

**Comment by paddyroddy** [comment]
I hadn't done that @mre, but now corrected and still having issues.

My composite action in full
```yaml
---
name: Links
description: Checks the links in a repo work

inputs:
  app-id:
    description: Application ID
    required: true

  app-pem:
    description: Application private key
    required: true

  lychee-args:
    description:
      Arguments to pass to lychee
      (https://github.com/lycheeverse/lychee#commandline-parameters)
    default: --no-progress --verbose .

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-pem }}

    - name: Check links
      uses: lycheeverse/lychee-action@f796c8b7d468feb9b8c0a46da3fac0af6874d374 # v2
      with:
        args: ${{ inputs.lychee-args }}
        failIfEmpty: false
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
```
and I am using in a different repo like this
```yaml
---
name: links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check links
        uses: UCL-MIRSG/.github/actions/links@75c9e4e574bdf8f9df1e681376f8816ef837a74e # v0
        with:
          app-id: ${{ secrets.LINK_APP_ID }}
          app-pem: ${{ secrets.LINK_APP_PEM }}
          lychee-args:
            --no-progress --verbose . --exclude https://mirsg-dev.cs.ucl.ac.uk
```
it is failing with
```
* [404] [https://github.com/UCL-MIRSG/mirsg-upgrades](https://github.com/UCL-MIRSG/mirsg-upgrades) | Network error: Not Found
```
`UCL-MIRSG/mirsg-upgrades` is indeed a private repository, so I'm quite confused.

**Comment by mre** [comment]
Oh, I meant you need to pass the token in the workflow. That's where the action gets executed, so that's where it needs the permission to access the repo. 

https://devops.pingidentity.com/how-to/privateRepos/#cloning-from-github-using-https

Don't think you need the composite action at all. You can just create a token once (from the GitHub settings) and add it as a secret to the workflow. Then you can get rid of the composite action.

**Comment by paddyroddy** [comment]
Anyone looking at this I've got it working

```yaml
---
name: Links
description: Checks the links in a repo work

inputs:
  app-id:
    description: Application ID
    required: true

  app-pem:
    description: Application private key
    required: true

  lychee-args:
    description:
      Arguments to pass to lychee
      (https://github.com/lycheeverse/lychee#commandline-parameters)
    default: --no-progress --verbose .

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1
      with:
        app-id: ${{ inputs.app-id }}
        owner: ${{ github.repository_owner }}
        private-key: ${{ inputs.app-pem }}

    - name: Check links
      uses: lycheeverse/lychee-action@f796c8b7d468feb9b8c0a46da3fac0af6874d374 # v2
      with:
        args: ${{ inputs.lychee-args }}
        failIfEmpty: false
        token: ${{ steps.generate-token.outputs.token }}
```

The key for me was that I was missing the `owner` section in `actions/create-github-app-token`. I want the composite action for our organisation just as a single point of truth.
